{{- $rootDomain := trimPrefix "{{ .Values.cluster.projectID }}." .Values.cluster.domain }}
sso-operator:
  dex:
    grpcHost: "dex.jx"
dex:
  domain: "dex-jx.{{ $rootDomain }}"
  connectors:
    google:
      config:
        type: oidc
        name: Google
        clientID: "{{ .Parameters.dashboardAuthID }}"
        clientSecret: "{{ .Parameters.dashboardAuthSecret }}"
        issuer: https://accounts.google.com
