replicaCount: 2
parentDomain: {{ .Parameters.parentDomain }}
parentProject: {{ .Parameters.parentProject}}
parentDNSZone: {{ .Parameters.parentDNSZone}}
basicAuthPassword: vault:jx-tenant-service-ba:password
dbUser: jx-tenant-service
dbPassword: vault:jx-tenant-service-db:password
cloudSQLSA: vault:jx-tenant-db-client:sa
sa: vault:jx-tenant-service-sa:json
saasSA: vault:jx-tenant-service-saas-sa:json
dbInstance: {{ .Parameters.tenantServiceDBInstance }}
service:
  serviceAnnotations:
    fabric8.io/expose: "false"
    fabric8.io/exposeUrl: https://jx-tenant-service{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain }}
