{{- $rootDomain := trimPrefix "{{ .Values.cluster.projectID }}." .Values.cluster.domain }} }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: arcalosui
spec:
  rules:
  # This domain MUST be first as the oauth proxy uses the first domain in the list to work out it's redirect url
  - host: dashboard.{{ $rootDomain }}
    http:
      paths:
        - backend:
            serviceName: sso-jenkins-x-arcalosui
            servicePort: 80
  - host: arcalosui{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
        - backend:
            serviceName: sso-jenkins-x-arcalosui
            servicePort: 80
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
      - dashboard.{{ $rootDomain }}
      - arcalosui{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
