apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: jx-tenant-service
spec:
  rules:
  - host: jx-tenant-service{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jx-tenant-service
          servicePort: 80
        path: /api/v1/(installation-id|domain|nameservers|version)$
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - jx-tenant-service{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}