{{- $rootDomain := trimPrefix "{{ .Values.cluster.projectID }}." .Values.cluster.domain }}
replicaCount: 2
skipExposeService: true
sso:
  create: true
  connector: google
  certIssuerName: letsencrypt-prod
  domain: "{{ $rootDomain }}"
  oidcIssuerUrl: "https://dex{{ .Requirements.ingress.namespaceSubDomain }}{{ $rootDomain }}"
roxApiKey: vault:rox:api-key
