replicaCount: 2
skipExposeService: true
sso:
  create: true
  connector: google
  certIssuerName: letsencrypt-prod
  domain: "{{ .Requirements.ingress.domain }}"
  oidcIssuerUrl: "https://dex{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain }}"
roxApiKey: vault:rox:api-key
service:
  serviceAnnotations:
    fabric8.io/expose: "false"
    fabric8.io/exposeUrl: https://arcalosui{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain }}
