dependencies:
- name: jxboot-resources
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.14
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.42
- alias: prow
  condition: prow.enabled
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.1344
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.157
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 2.0.1376
- name: jx-app-sso
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.19
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- alias: jx-app-kuberhealthy
  condition: jx-app-kuberhealthy.enabled
  name: jx-app-kuberhealthy
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.2
- alias: ui
  name: jxui
  repository: https://charts.cloudbees.com/cjxd/cloudbees
  version: 0.0.879
- name: jx-tenant-service
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.69
- name: arcalosui
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.61
